[project]
name = "BE"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.117.1",
    "google-genai>=1.39.0",
    "httpx>=0.28.1",
    "pwdlib[argon2]>=0.3.0",
    "pyjwt>=2.10.1",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
]


[tool.coverage.run]
omit = [
    "app/db/fake_db.py",
    "app/db/init_db.py",
]